general {
    lock_cmd = pidof hyprlock || hyprlock       # evita lanzar varios hyprlock
    before_sleep_cmd = loginctl lock-session     # bloquea antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on   # enciende pantalla al despertar
}

# Atenúa nada / apaga pantalla a los 5 min
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Bloquea la pantalla a los 10 min
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
