preload = /home/fazt/Pictures/Wallpapers/dark-radial.png

# Fondo negro en las tres pantallas
wallpaper = HDMI-A-1, /home/fazt/Pictures/Wallpapers/dark-radial.png
wallpaper = DP-1, /home/fazt/Pictures/Wallpapers/dark-radial.png
wallpaper = DP-2, /home/fazt/Pictures/Wallpapers/dark-radial.png
# Y cualquier monitor futuro
wallpaper = , /home/fazt/Pictures/Wallpapers/dark-radial.png

splash = false
ipc = on
